"""Pfadilageranmeldung v0.4

Revision ID: 05086fad231b
Revises: da807f5aef8f
Create Date: 2023-08-27 14:33:10.235287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05086fad231b'
down_revision = 'da807f5aef8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pfadilageranmeldung', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vorname', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('nachname', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pfadilageranmeldung', schema=None) as batch_op:
        batch_op.drop_column('nachname')
        batch_op.drop_column('vorname')

    # ### end Alembic commands ###
