"""pfadiLager v.01

Revision ID: 307a5dd30cda
Revises: c23613289584
Create Date: 2023-08-27 01:00:39.319398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307a5dd30cda'
down_revision = 'c23613289584'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pfadi_lager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('datum', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pfadi_lager')
    # ### end Alembic commands ###
