"""Pfadilageranmeldung

Revision ID: 35e5b0776dda
Revises: 693649aa407b
Create Date: 2023-08-27 02:29:37.893103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35e5b0776dda'
down_revision = '693649aa407b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pfadilageranmeldung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pfadilager_id', sa.Integer(), nullable=False),
    sa.Column('pfadikind_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pfadikind_id'], ['pfadikind.id'], ),
    sa.ForeignKeyConstraint(['pfadilager_id'], ['pfadilager.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pfadilageranmeldung')
    # ### end Alembic commands ###
