"""users tables v1.0

Revision ID: 4a354b498094
Revises: e37cdd369e85
Create Date: 2023-08-25 19:46:16.700390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a354b498094'
down_revision = 'e37cdd369e85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vorname', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('nachname', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('nachname')
        batch_op.drop_column('vorname')

    # ### end Alembic commands ###
