"""admin

Revision ID: 849d156dab5a
Revises: 05086fad231b
Create Date: 2023-08-27 15:26:19.236156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '849d156dab5a'
down_revision = '05086fad231b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
