"""register_pfadikind

Revision ID: a7202987063f
Revises: 4a354b498094
Create Date: 2023-08-26 21:05:57.924488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7202987063f'
down_revision = '4a354b498094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pfadikind',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pfadiname', sa.String(length=64), nullable=True),
    sa.Column('vegetarisch', sa.Boolean(), nullable=True),
    sa.Column('vorname', sa.String(length=64), nullable=True),
    sa.Column('nachname', sa.String(length=64), nullable=True),
    sa.Column('geburtsdatum', sa.Date(), nullable=True),
    sa.Column('adresse', sa.String(length=128), nullable=True),
    sa.Column('telefonprivat', sa.String(length=20), nullable=True),
    sa.Column('telefonberuflich', sa.String(length=20), nullable=True),
    sa.Column('allergien_unvertraeglichkeiten', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pfadikind')
    # ### end Alembic commands ###
